version: '3.1'
services:
  Draco:
    image: ging/fiware-Draco
    container_name: Draco
    environment:
      - NIFI_WEB_HTTP_PORT=9090
    ports:
      - "9090:9090"
      - "5050:5050"
  mysql-db:
    image: mysql:5.7.22
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"
